openapi: 3.0.1
info:
  title: Events Counter
  version: v1.0.0
  description: '

    API documentation for Events Counter <br/>

    <br/>

    <p>Some terms you should know</p>

    <p> - Asset: It is something on which you are going to have an event. Eg: a web
    page, a screen in mobile app, a button. It can be anything. </p>

    <p> - Event: The event you want to count. Eg: page views, button clicks etc. </p>

    <p> - Count: The number representing the count for an event. </p>

    <p> - Step: It is the number by which to increment or decrement the count. Tip:
    To decrement by one pass <code>-1</code> </p>

    '
  contact:
    name: Events Counter
    url: https://www.therdnotes.com/projects/events-counter
servers:
- url: http://localhost:8080/
  description: Local Dev
paths:
  /counts:
    get:
      tags:
      - Counts
      summary: Gets the counts
      operationId: getCounts
      parameters:
      - name: asset_id
        in: query
        description: Unique ID of the Asset
        required: false
        schema:
          type: string
      - name: event_id
        in: query
        description: Unique ID of the Event
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCounts'
              example:
                counts:
                - assetId: home-page
                  eventId: page-views
                  count: 80482
                - assetId: blog/terminal-setup
                  eventId: up-vote
                  count: 240
                - assetId: blog/terminal-setup
                  eventId: claps
                  count: 4028
        '401':
          description: Un-Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
              example:
                contextId: 848b30d5-0d6e-42e6-845e-92e3eb87dff3
                code: 401
                message: UNAUTHORIZED
      security:
      - httpAuth: []
    post:
      tags:
      - Counts
      summary: Submit the counts to add/subtract for different asset/event combination
      operationId: postCounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCountsRequest'
            example:
              counts:
              - assetId: home-page
                eventId: page-views
                stepBy: 1
              - assetId: blog/terminal-setup
                eventId: up-vote
                stepBy: -1
              - assetId: blog/terminal-setup
                eventId: claps
                stepBy: 40
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCounts'
              example:
                counts:
                - assetId: home-page
                  eventId: page-views
                  count: 80482
                - assetId: blog/terminal-setup
                  eventId: up-vote
                  count: 240
                - assetId: blog/terminal-setup
                  eventId: claps
                  count: 4028
        '401':
          description: Un-Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
              example:
                contextId: 848b30d5-0d6e-42e6-845e-92e3eb87dff3
                code: 401
                message: UNAUTHORIZED
      security:
      - httpAuth: []
components:
  schemas:
    ErrorInfo:
      required:
      - contextId
      - code
      - message
      type: object
      properties:
        contextId:
          type: string
        code:
          type: integer
        message:
          type: string
    GetCounts:
      type: object
      properties:
        counts:
          type: array
          items:
            $ref: '#/components/schemas/Count'
    Count:
      required:
      - assetId
      - eventId
      - count
      type: object
      properties:
        assetId:
          type: string
        eventId:
          type: string
        count:
          type: integer
    PostCountsRequest:
      type: object
      properties:
        counts:
          type: array
          items:
            $ref: '#/components/schemas/Step'
    Step:
      required:
      - assetId
      - eventId
      - stepBy
      type: object
      properties:
        assetId:
          type: string
        eventId:
          type: string
        stepBy:
          type: integer
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
